# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='company_field',
            field=models.CharField(default='Firma', max_length=100),
        ),
        migrations.AddField(
            model_name='provider',
            name='establishment_date',
            field=models.CharField(default='Ezelden beri', max_length=40),
        ),
    ]
