# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 12:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_intview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 12, 17, 38, 908871, tzinfo=utc)),
        ),
    ]
