# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170826_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
