# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170826_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
