# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20170828_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='liseli',
            name='lise',
            field=models.CharField(default='Aradığın Lise Yok Mu?', max_length=150),
        ),
    ]
