# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20170828_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liseli',
            name='lise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Lise'),
        ),
    ]
