# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20170828_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liseli',
            name='grade',
            field=models.CharField(choices=[('Choose', '---Sınıfını Seç---'), ('Prep', 'Hazırlık'), ('9', '9. sınıf'), ('10', '10. sınıf'), ('11', '11. sınıf'), ('12', '12. sınıf'), ('Done', 'Liseyi Bitirdim')], default='Hazırlık', max_length=100),
        ),
    ]
